// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway-comm.proto

package org.gateway.protos;

public interface DownloadResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.DownloadResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Will return the node information to connect with
   * </pre>
   *
   * <code>string nodeip = 1;</code>
   * @return The nodeip.
   */
  java.lang.String getNodeip();
  /**
   * <pre>
   * Will return the node information to connect with
   * </pre>
   *
   * <code>string nodeip = 1;</code>
   * @return The bytes for nodeip.
   */
  com.google.protobuf.ByteString
      getNodeipBytes();

  /**
   * <pre>
   * Will return ERROR or SUCCESS
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Will return ERROR or SUCCESS
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
