// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway-comm.proto

package org.gateway.protos;

public final class GatewayComm {
  private GatewayComm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stream_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_Reply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stream_Reply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022gateway-comm.proto\022\006stream\")\n\007Request\022" +
      "\014\n\004name\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"\031\n\005Reply" +
      "\022\020\n\010masterip\030\001 \001(\t2<\n\014Authenticate\022,\n\010Re" +
      "gister\022\017.stream.Request\032\r.stream.Reply\"\000" +
      "B\026\n\022org.gateway.protosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_stream_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_stream_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stream_Request_descriptor,
        new java.lang.String[] { "Name", "Password", });
    internal_static_stream_Reply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_stream_Reply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stream_Reply_descriptor,
        new java.lang.String[] { "Masterip", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
