// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway-comm.proto

package org.gateway.protos;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string client_ip = 1;</code>
   * @return The clientIp.
   */
  java.lang.String getClientIp();
  /**
   * <code>string client_ip = 1;</code>
   * @return The bytes for clientIp.
   */
  com.google.protobuf.ByteString
      getClientIpBytes();

  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
