// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway-comm.proto

package org.gateway.protos;

public interface ReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.Reply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string masterip = 1;</code>
   * @return The masterip.
   */
  java.lang.String getMasterip();
  /**
   * <code>string masterip = 1;</code>
   * @return The bytes for masterip.
   */
  com.google.protobuf.ByteString
      getMasteripBytes();
}
