// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway-comm.proto

package org.gateway.protos;

public interface UploadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.UploadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string client_ip = 1;</code>
   * @return The clientIp.
   */
  java.lang.String getClientIp();
  /**
   * <code>string client_ip = 1;</code>
   * @return The bytes for clientIp.
   */
  com.google.protobuf.ByteString
      getClientIpBytes();

  /**
   * <code>string filename = 2;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 2;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <pre>
   * in bytes
   * </pre>
   *
   * <code>int64 filesize = 3;</code>
   * @return The filesize.
   */
  long getFilesize();

  /**
   * <code>string token = 4;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 4;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
