// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway-comm.proto

package org.gateway.protos;

public interface ValidateTokenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.ValidateTokenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string client_ip = 1;</code>
   * @return The clientIp.
   */
  java.lang.String getClientIp();
  /**
   * <code>string client_ip = 1;</code>
   * @return The bytes for clientIp.
   */
  com.google.protobuf.ByteString
      getClientIpBytes();

  /**
   * <code>string token = 2;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 2;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
