// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway-comm.proto

package org.gateway.protos;

public interface ValidateTokenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stream.ValidateTokenResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * returns VALID or INVALID
   * </pre>
   *
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * returns VALID or INVALID
   * </pre>
   *
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
