// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master-comm.proto

package org.master.protos;

public final class MasterComm {
  private MasterComm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_NewNodeUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stream_NewNodeUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_StatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stream_StatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_GetNodeForDownloadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stream_GetNodeForDownloadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_GetNodeForDownloadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stream_GetNodeForDownloadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_GetNodeForUploadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stream_GetNodeForUploadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stream_GetNodeForUploadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stream_GetNodeForUploadResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021master-comm.proto\022\006stream\")\n\024NewNodeUp" +
      "dateRequest\022\021\n\tnewnodeip\030\001 \001(\t\"0\n\016Status" +
      "Response\022\036\n\006status\030\001 \001(\0162\016.stream.Status" +
      "\"-\n\031GetNodeForDownloadRequest\022\020\n\010filenam" +
      "e\030\001 \001(\t\",\n\032GetNodeForDownloadResponse\022\016\n" +
      "\006nodeip\030\001 \001(\t\"=\n\027GetNodeForUploadRequest" +
      "\022\020\n\010filename\030\001 \001(\t\022\020\n\010filesize\030\002 \001(\003\"*\n\030" +
      "GetNodeForUploadResponse\022\016\n\006nodeip\030\001 \001(\t" +
      "*\"\n\006Status\022\013\n\007SUCCESS\020\000\022\013\n\007FAILURE\020\0012\216\002\n" +
      "\013Replication\022G\n\rNewNodeUpdate\022\034.stream.N" +
      "ewNodeUpdateRequest\032\026.stream.StatusRespo" +
      "nse\"\000\022]\n\022GetNodeForDownload\022!.stream.Get" +
      "NodeForDownloadRequest\032\".stream.GetNodeF" +
      "orDownloadResponse\"\000\022W\n\020GetNodeForUpload" +
      "\022\037.stream.GetNodeForUploadRequest\032 .stre" +
      "am.GetNodeForUploadResponse\"\000B\025\n\021org.mas" +
      "ter.protosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_stream_NewNodeUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_stream_NewNodeUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stream_NewNodeUpdateRequest_descriptor,
        new java.lang.String[] { "Newnodeip", });
    internal_static_stream_StatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_stream_StatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stream_StatusResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_stream_GetNodeForDownloadRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_stream_GetNodeForDownloadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stream_GetNodeForDownloadRequest_descriptor,
        new java.lang.String[] { "Filename", });
    internal_static_stream_GetNodeForDownloadResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_stream_GetNodeForDownloadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stream_GetNodeForDownloadResponse_descriptor,
        new java.lang.String[] { "Nodeip", });
    internal_static_stream_GetNodeForUploadRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_stream_GetNodeForUploadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stream_GetNodeForUploadRequest_descriptor,
        new java.lang.String[] { "Filename", "Filesize", });
    internal_static_stream_GetNodeForUploadResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_stream_GetNodeForUploadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stream_GetNodeForUploadResponse_descriptor,
        new java.lang.String[] { "Nodeip", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
